### ISSUE TITLE
Driveアクセスのsuspendでのラップ箇所修正

### ISSUE THREAD

**Issue by harukawa** [harukawa/DriveText#30]
GoogleDriveとのアクセスを行うsuspend関数が機能していないので修正を行う。

**Comment by karino2** [comment]
これは自信が無ければPR作った段階でマージの前に私がレビューしてもいいですよ。
（特に分からない所が無ければそのままマージしてしまってもいいです。どちらでもお好きな方で）

**Comment by harukawa** [comment]
作れましたが少し不安なのでレビューをお願いします。
startActivityForResultはuploadとupdateでうまくエラーを出せなかったので、別に試しましたがDispatchers.IOで動きました。
#33

**Comment by karino2** [comment]
了解です。そこが動けば、それ以外のコードは問題無いと思います。
マージしちゃってください。

**Comment by harukawa** [comment]
ありがとうございます。マージします。
